### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by robkam** [saveweb/wikiteam3#20]
`$ wikiteam3dumpgenerator https://scruff.miraheze.org/w/api.php --xml --images --bypass-cdn-image-compression --force --user USER --pass PASSWORD > scruff.txt`

[snipped]

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Python\Scripts\wikiteam3dumpgenerator.exe\__main__.py", line 7, in <module>
  File "C:\Python\Lib\site-packages\wikiteam3\dumpgenerator\__init__.py", line 7, in main
    DumpGenerator()
  File "C:\Python\Lib\site-packages\wikiteam3\dumpgenerator\dump\generator.py", line 86, in __init__
    DumpGenerator.createNewDump(config=config, other=other)
  File "C:\Python\Lib\site-packages\wikiteam3\dumpgenerator\dump\generator.py", line 117, in createNewDump
    Image.generate_image_dump(
  File "C:\Python\Lib\site-packages\wikiteam3\dumpgenerator\dump\image\image.py", line 348, in generate_image_dump
    print(f'{len(images)}=>{filename_underscore}')
  File "C:\Python\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode character '\u0105' in position 17: character maps to <undefined>
```

Needs ` encode("utf-8")` and `encoding="utf-8"
`

**Comment by yzqzss** [comment]
Windows is shit

**Comment by yzqzss** [comment]
You are using cp1252 :)

**Comment by robkam** [comment]
`$ set PYTHONIOENCODING=utf-8` doesn't fix it.

**Comment by yzqzss** [comment]
CHECK YOUR SHIT TERMINAL
