### ISSUE TITLE
Doesn't login on private wiki

### ISSUE THREAD

**Issue by robkam** [saveweb/wikiteam3#5]
<details>
```
$ git clone https://github.com/saveweb/wikiteam3

$ git checkout --track origin/cli-options

$ poetry update && poetry install && poetry build

$ pip install --force-reinstall dist/*.whl

$ dumpgenerator  --xml --xmlrevisions --images --user USER --pass PASSWORD --api https://scruffy.miraheze.org/w/api.php  --index https://scruffy.miraheze.org/wiki/index.php
Checking API... https://scruffy.miraheze.org/w/api.php
MediaWiki API seems to work but returned no index URL
API is OK:  https://scruffy.miraheze.org/w/api.php
Trying to log in to the wiki using clientLogin... (MW 1.27+)
client login: Success! Welcome, USER!
-- Login OK --
Checking index.php... https://scruffy.miraheze.org/wiki/index.php
ERROR: This wiki requires login and we are not authenticated
Error in index.php.
No --path argument provided. Defaulting to:
  [working_directory]/[domain_prefix]-[date]-wikidump
Which expands to:
  ./scruffymirahezeorg_w-20230220-wikidump
--delay is the default value of 0.5
There will be a 0.5 second delay between HTTP calls in order to keep the server from timing you out.
If you know that this is unnecessary, you can manually specify '--delay 0.0'.

... snipped ...

Analysing https://scruffy.miraheze.org/w/api.php
Trying generating a new dump into a new directory...
https://scruffy.miraheze.org/w/api.php
Getting the XML header from the API
Export test via the API failed. Wiki too old? Trying without xmlrevisions.
https://scruffy.miraheze.org/w/api.php
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Python\Scripts\dumpgenerator.exe\__main__.py", line 7, in <module>
  File "C:\Python\Lib\site-packages\wikiteam3\dumpgenerator\__init__.py", line 26, in main
    DumpGenerator()
  File "C:\Python\Lib\site-packages\wikiteam3\dumpgenerator\dump\generator.py", line 115, in __init__
    DumpGenerator.createNewDump(config=config, other=other)
  File "C:\Python\Lib\site-packages\wikiteam3\dumpgenerator\dump\generator.py", line 128, in createNewDump
    generateXMLDump(config=config, session=other["session"])
  File "C:\Python\Lib\site-packages\wikiteam3\dumpgenerator\dump\xmldump\xml_dump.py", line 96, in generateXMLDump
    header, config = getXMLHeader(config=config, session=session)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\wikiteam3\dumpgenerator\dump\xmldump\xml_header.py", line 124, in getXMLHeader
    header, config = getXMLHeader(config=config, session=session)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\wikiteam3\dumpgenerator\dump\xmldump\xml_header.py", line 70, in getXMLHeader
    [
  File "C:\Python\Lib\site-packages\wikiteam3\dumpgenerator\dump\xmldump\xml_header.py", line 70, in <listcomp>
    [
  File "C:\Python\Lib\site-packages\wikiteam3\dumpgenerator\dump\page\xmlexport\page_xml_export.py", line 117, in getXMLPageWithExport
    xml = getXMLPageCore(params=params, config=config, session=session)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\wikiteam3\dumpgenerator\dump\page\xmlexport\page_xml_export.py", line 76, in getXMLPageCore
    r = session.post(
        ^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\requests\sessions.py", line 635, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\wikiteam3\utils\user_agent.py", line 324, in newrequest
    return session._orirequest(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\requests\sessions.py", line 573, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\requests\sessions.py", line 484, in prepare_request
    p.prepare(
  File "C:\Python\Lib\site-packages\requests\models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "C:\Python\Lib\site-packages\requests\models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL 'None': No scheme supplied. Perhaps you meant https://None?
```
</details>

**Comment by robkam** [comment]
When the wiki is set to public the dump runs okay.

**Comment by yzqzss** [comment]
`saveweb:cli-options` branch is not for fixing this issue.

Dup: https://github.com/mediawiki-client-tools/mediawiki-scraper/issues/118
