### ISSUE TITLE
[TODO]: Handle `MWUnknownContentModelException`

### ISSUE THREAD

**Issue by yzqzss** [saveweb/wikiteam3#7]
`cz https://minecraftonline.com/wiki/Main_Page`

```
File:Swissm4ns experimental forest.png, 1 edits (--xmlrevisions)            Swissm4n's experimental forest, 1 edits (--xmlrevisions)                    [arvcontinue]: 20210301111422|59076                                         Traceback (most recent call last):                                            File "/home/yzqzss/python3.11_venv/bin/wikiteam3dumpgenerator", line 8, in <module>                                                                       sys.exit(main())                                                                     ^^^^^^                                                           File "/home/yzqzss/python3.11_venv/lib/python3.11/site-packages/wikiteam3/dumpgenerator/__init__.py", line 5, in main
    DumpGenerator()                                                           File "/home/yzqzss/python3.11_venv/lib/python3.11/site-packages/wikiteam3/dumpgenerator/dump/generator.py", line 103, in __init__                         DumpGenerator.createNewDump(config=config, other=other)                   File "/home/yzqzss/python3.11_venv/lib/python3.11/site-packages/wikiteam3/dumpgenerator/dump/generator.py", line 129, in createNewDump                    generate_XML_dump(config=config, session=other["session"])                File "/home/yzqzss/python3.11_venv/lib/python3.11/site-packages/wikiteam3/dumpgenerator/dump/xmldump/xml_dump.py", line 144, in generate_XML_dump         doXMLRevisionDump(config, session, xmlfile, lastPage, useAllrevisions=True)                                                                           File "/home/yzqzss/python3.11_venv/lib/python3.11/site-packages/wikiteam3/dumpgenerator/dump/xmldump/xml_dump.py", line 29, in doXMLRevisionDump          for xml in getXMLRevisions(config=config, session=session, lastPage=lastPage, useAllrevision=useAllrevisions):                                        File "/home/yzqzss/python3.11_venv/lib/python3.11/site-packages/wikiteam3/dumpgenerator/dump/page/xmlrev/xml_revisions.py", line 72, in getXMLRevisionsByAllRevisions
    allrevs_response = site.api(
                       ^^^^^^^^^
  File "/home/yzqzss/python3.11_venv/lib/python3.11/site-packages/mwclient/client.py", line 288, in api
    if self.handle_api_result(info, sleeper=sleeper):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yzqzss/python3.11_venv/lib/python3.11/site-packages/mwclient/client.py", line 333, in handle_api_result
    raise errors.APIError(info['error']['code'],
mwclient.errors.APIError: ('internal_api_error_MWUnknownContentModelException', '[9edcfa90c2e3cf303985ba0c] Caught exception of type MWUnknownContentModelException', None)
```

**Comment by yzqzss** [comment]
https://cdn.digitaldragon.dev/wikibot/jobs/1455afe2-286b-4d14-b054-dbb5a5e9c7f5/log.txt
